spring.application.name=ai_requirement_be
spring.datasource.username=postgres
spring.datasource.password=hung404*
spring.datasource.url=jdbc:postgresql://localhost:5432/job_application
logging.level.org.springframework.context.annotation=DEBUG
jwt.secret=chuoibimatnayphaithatla_daidai_daidai_daidai_daidai_daidai_daidai
jwt.access-expiration=90000
jwt.refresh-expiration=604800000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=TRACE