spring.application.name=ai_requirement_be
spring.datasource.username=postgres
spring.datasource.password=hung404*
spring.datasource.url=jdbc:postgresql://localhost:5432/job_application
logging.level.org.springframework.context.annotation=DEBUG
jwt.secret=chuoibimatnayphaithatla_daidai_daidai_daidai_daidai_daidai_daidai
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

