spring.application.name=ai_requirement_be
spring.datasource.username=postgres
spring.datasource.password=admin1
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_recruiment
logging.level.org.springframework.context.annotation=DEBUG
jwt.secret=chuoibimatnayphaithatla_daidai_daidai_daidai_daidai_daidai_daidai
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.transaction=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB